version: '3.7'

services:
  fastapi:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    volumes:
      - .:/app
    ports:
      - 80:8000
    environment:
      - API_REDIS_HOST=redis
    expose:
      - db
      - redis

  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=dan
    expose:
      - 5432


  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - 6379:6379

volumes:
  postgres_data:
